alias: 'Disarm'
trigger:
  - platform: state
    entity_id: input_select.alarm_select
    to: 'Disarmed'
  - platform: state
    entity_id: input_boolean.disarm_the_alarm
    to: 'on'
action:
  - service: script.turn_on
    entity_id: script.alarm_disarm
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.ha_alarm
  - service: input_boolean.turn_off
    entity_id: input_boolean.disarm_the_alarm
