alias: 'Disarm alarm home at the morning'
trigger:
  - platform: time
    at: '06:45:00'
condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: 'armed_home'
action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.ha_alarm