- action:
  - alias: light_kontor
    data:
      entity_id: light.tradfri_bulb_e27_opal_1000lm_2
    service: light.turn_on
  alias: Kontoret_light
  id: '1501424467392'
  trigger:
  - entity_id: binary_sensor.kontoret_sensor
    from: 'off'
    platform: state
    to: 'on'
- action:
  - alias: kontoret_av
    data:
      entity_id: light.tradfri_bulb_e27_opal_1000lm_2
    service: light.turn_off
  alias: kontoret_light_off
  id: '1501424703385'
  trigger:
  - entity_id: binary_sensor.kontoret_sensor
    from: 'on'
    platform: state
    to: 'off'
    for:
      minutes: 10
- id: hej001
  alias: "Utebelysning p\xE5 solnedg\xE5ng"
  trigger:
  - event: sunset
    platform: sun
  action:
  - data:
      entity_id: switch.utebelysning_switch
    service: switch.turn_on
- id: hej002
  alias: "Utebelysning av soluppg\xE5ng"
  trigger:
  - platform: sun
    event: sunrise
  action:
  - service: switch.turn_off
    entity_id: switch.utebelysning_switch


- id: hej003
  alias: "Markis upp vid solnedg\xE5ng"
  trigger:
  - platform: sun
    event: sunset
  action:
  - data:
      entity_id: cover.markis_allrum_switch
  - service: cover.open_cover
