alias: 'God morgon, radio rörelse på morgonen'
trigger:
  - platform: state
    entity_id: binary_sensor.hallen_sensor
    to: 'on'
condition:
  - condition: time
    after: '06:00:00'
    before: '10:00:00'
  - condition: state
    entity_id: input_boolean.trigger_first_morning
    state: 'off'
action:
  - service: script.turn_on
    entity_id: script.google_home_good_morning
  - service: homeassistant.turn_on
    entity_id: input_boolean.trigger_first_morning