alias: 'Lampa på hallen'
trigger:
  - platform: state
    entity_id: binary_sensor.hallen_sensor
    to: 'on'
condition:
  - condition: numeric_state
    entity_id: sensor.hallen_luminance
    below: 30
action:
  - service: light.turn_on
    entity_id: light.taklampa_hallen
    data:
      brightness: 150
  - service: light.turn_on
    entity_id: light.nedanfor_trappen
    data:
      brightness: 150