alias: 'Lampa på i tvättstuga'
trigger:
  - platform: state
    entity_id: binary_sensor.tvattstuga_sensor
    to: 'on'
condition:
  - condition: numeric_state
    entity_id: sensor.tvattstuga_luminance
    below: 150
action:
  - service: light.turn_on
    entity_id: light.tvattstuga
    data:
      brightness: 255