alias: 'Fönsterbelysning av kl 22'
trigger:
  - platform: time
    at: '22:00:00'
action:
  - service: switch.turn_off
    entity_id: switch.fonsterbelysning_kamin_switch
  - service: switch.turn_off
    entity_id: switch.fonsterbelysning_tehorna_switch