alias: 'Fönsterbelysning på solnedgång'
trigger:
  - platform: sun
    event: sunset
action:
  - service: switch.turn_on
    entity_id: switch.fonsterbelysning_kamin_switch
  - service: switch.turn_on
    entity_id: switch.fonsterbelysning_tehorna_switch